name: scan-api
on:
  release:
    types: [published]
  label:
    types:
      - created

jobs:
  scan-autogen:
    env:
      HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
      HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
      HW_REGION_NAME: cn-north-4
      HW_ENTERPRISE_PROJECT_ID: "0"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: chnsz/terraform-provider-generator
          token: ${{ secrets.GH_PAT }}
          path: scan_1

      # run acceptance test
      - run: |
          ls -l
          cd scan_1
          ls -l
          